select cont.*,doc.USA_PLANTILLA
from documento doc
inner join contenido cont on cont.ID_CONTENIDO=doc.ID_CONTENIDO;

select *
from contenido 
where EXTENSION in('MP4','PDF');

select distinct cont.*
from se_clasifica_en claf
inner join contenido cont on cont.ID_CONTENIDO = claf.ID_CONTENIDO
inner join categoria cat on cat.ID_CATEGORIA = claf.ID_CATEGORIA
where cat.TIPO in ('BASICO','ULTRA')
order by cont.ID_CONTENIDO desc;

SELECT *
FROM CONTENIDO 
WHERE TITULO LIKE '%N%';

INSERT  CONTENIDO (TITULO,FECHA_PUBLICADO,EXTENSION,URL) VALUES('AGREGACION DE CONTENIDO','2021-05-01','MP4','https://drive.google.com/drive/u/0/folders/AGREGACION DE CONTENIDO.MP4');

SELECT * FROM CONTENIDO;

DELETE FROM CONTENIDO
WHERE ID_CONTENIDO=51;

SELECT CTN.EXTENSION, COUNT(ES_DESCARGADO.ID_CONTENIDO) CANTIDAD_ARCHIVOS_DESCARGADOS
FROM contenido CTN
RIGHT JOIN descargable DSC ON DSC.ID_CONTENIDO = CTN.ID_CONTENIDO
LEFT JOIN ES_DESCARGADO ON ES_DESCARGADO.ID_CONTENIDO = DSC.ID_CONTENIDO
GROUP BY CTN.EXTENSION;



SELECT CTN.EXTENSION,COUNT(MIRA.ID_CONTENIDO) CANTIDAD_DE_VIDEOS_VISTOS
FROM contenido CTN
INNER JOIN VIDEO VD ON VD.ID_CONTENIDO = CTN.ID_CONTENIDO
INNER JOIN MIRA ON MIRA.ID_CONTENIDO = VD.ID_CONTENIDO
GROUP BY CTN.EXTENSION;



SELECT CTN.TITULO, COUNT(ES_DESCARGADO.ID_CONTENIDO) CANTIDAD_ARCHIVOS_DESCARGADOS
FROM contenido CTN
RIGHT JOIN descargable DSC ON DSC.ID_CONTENIDO = CTN.ID_CONTENIDO
LEFT JOIN ES_DESCARGADO ON ES_DESCARGADO.ID_CONTENIDO = DSC.ID_CONTENIDO
GROUP BY CTN.TITULO;



SELECT CTN.TITULO,COUNT(MIRA.ID_CONTENIDO) CANTIDAD_DE_VIDEOS_VISTOS
FROM contenido CTN
INNER JOIN VIDEO VD ON VD.ID_CONTENIDO = CTN.ID_CONTENIDO
INNER JOIN MIRA ON MIRA.ID_CONTENIDO = VD.ID_CONTENIDO
GROUP BY CTN.ID_CONTENIDO;



select cont.*
from se_clasifica_en claf
inner join contenido cont on cont.ID_CONTENIDO = claf.ID_CONTENIDO
inner join categoria cat on cat.ID_CATEGORIA = claf.ID_CATEGORIA
where cat.TIPO in ('BASICO','ULTRA')
group by cont.ID_CONTENIDO 
having count(distinct cat.tipo) = 2;
